# Setup
title: Seohyeon Park
description: Hi! I'm an MS-PhD integrated student at PILAB, SNU. My main research interests are VLA and 3D Vision.  
url: https://eainx.github.io
avatar: assets/profile.jpg
paginate: 5
permalink: pretty
cover_image: 

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag

logo: logo.png
social:
  name: Seohyeon Park
  links:
    - https://github.com/eainx
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Seohyeon Park
  url: https://eainx.github.io
  email: seohyun423@korea.ac.kr
  
plugins:
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole
